import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { useAccessToken } from '../auth/authSession';
import { archiveBudget, createBudget, evaluateBudgets, fetchBudgetAlerts, fetchBudgetPerformance, fetchBudgets, fetchCostDataOptions, updateBudget, type Budget, type BudgetPerformance, type BudgetScope, type CostDataOptions } from '../services/api';

type Alert = { readonly id: string; readonly level: string; readonly createdAt: string };

export default function Budgets({ canManage, onOpenAllocation }: { readonly canManage: boolean; readonly onOpenAllocation: () => void }) {
  const token = useAccessToken();
  const [period, setPeriod] = useState(currentMonth()); const [cloudAccountId, setCloudAccountId] = useState(''); const [serviceName, setServiceName] = useState('');
  const [options, setOptions] = useState<CostDataOptions | null>(null); const [budgets, setBudgets] = useState<readonly Budget[]>([]); const [performance, setPerformance] = useState<Record<string, BudgetPerformance>>({}); const [alerts, setAlerts] = useState<Record<string, readonly Alert[]>>({});
  const [creating, setCreating] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const load = useCallback(async () => {
    setLoading(true); const result = await fetchBudgets(token, { period, ...(cloudAccountId === '' ? {} : { cloudAccountId }), ...(serviceName === '' ? {} : { serviceName }) });
    const details = await Promise.allSettled(result.budgets.map(async (budget) => [await fetchBudgetPerformance(token, budget.id), await fetchBudgetAlerts(token, budget.id)] as const));
    const completed = details.filter((item) => item.status === 'fulfilled').map((item) => (item as PromiseFulfilledResult<readonly [{ readonly success: true; readonly performance: BudgetPerformance }, { readonly success: true; readonly alerts: readonly Alert[] }]>).value);
    setBudgets(result.budgets); setPerformance(Object.fromEntries(completed.map(([detail]) => [detail.performance.budget.id, detail.performance])));
    setAlerts(Object.fromEntries(completed.map(([detail, budgetAlerts]) => [detail.performance.budget.id, budgetAlerts.alerts])));
    setError(details.some((item) => item.status === 'rejected') ? 'Algunos indicadores de presupuesto no se pudieron actualizar. Puede volver a evaluar el presupuesto.' : null); setLoading(false);
  }, [cloudAccountId, period, serviceName, token]);
  useEffect(() => { void fetchCostDataOptions(token, period).then((value) => setOptions(value.options)).catch(() => setOptions(null)); }, [period, token]);
  useEffect(() => { const timer = window.setTimeout(() => { void load().catch((cause) => { setError(message(cause, 'No fue posible cargar presupuestos.')); setLoading(false); }); }); return () => window.clearTimeout(timer); }, [load]);
  const create = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { const scope = String(form.get('scope')) as BudgetScope; await createBudget(token, { scope, period, amount: Number(form.get('amount')), currency: String(form.get('currency')).toUpperCase(), warningThreshold: Number(form.get('warningThreshold')) / 100, criticalThreshold: Number(form.get('criticalThreshold')) / 100, exceededThreshold: Number(form.get('exceededThreshold')) / 100, ...(scope === 'ALLOCATION_DESTINATION' ? { scopeKey: String(form.get('scopeKey')).trim() } : {}), ...(scope === 'SERVICE' ? { serviceName: String(form.get('serviceName')) } : {}), ...(scope === 'CLOUD_ACCOUNT' ? { cloudAccountId: String(form.get('cloudAccountId')) } : {}) }); setCreating(false); setNotice('Presupuesto creado. Los umbrales se evaluarán con el gasto del período seleccionado.'); await load(); } catch (cause) { setError(message(cause, 'No fue posible crear el presupuesto.')); } };
  const edit = async (budget: Budget) => { const amount = window.prompt('Importe mensual', String(budget.amount)); if (amount === null || !Number.isFinite(Number(amount)) || Number(amount) <= 0) return; try { await updateBudget(token, budget.id, { amount: Number(amount) }); setNotice('Importe actualizado.'); await load(); } catch (cause) { setError(message(cause, 'No fue posible actualizar el presupuesto.')); } };
  const latestHint = options?.latestPeriod !== undefined && options.latestPeriod !== period ? `El último período con costos disponibles es ${options.latestPeriod}.` : null;
  return <div className="ui-page space-y-6"><header className="ui-page-header"><div><p className="ui-kicker">Control financiero</p><h1 className="ui-page-title mt-2">Presupuestos</h1><p className="ui-page-lead">Defina un límite mensual, revise el gasto real y anticípese al forecast.</p></div><div className="flex flex-wrap gap-2"><input aria-label="Período de presupuesto" type="month" value={period} onChange={(event) => setPeriod(event.target.value)} className={fieldClass}/>{canManage && <button onClick={() => setCreating((value) => !value)} className="ui-button ui-button-primary">Nuevo presupuesto</button>}</div></header>
    {latestHint !== null && <Hint text={latestHint} onUse={() => setPeriod(options!.latestPeriod!)} />}
    <div className="grid gap-3 md:grid-cols-2"><Select value={cloudAccountId} onValueChange={setCloudAccountId} label="Cuenta cloud"><option value="">Todas las cuentas</option>{(options?.cloudAccounts ?? []).map((account) => <option key={account.id} value={account.id}>{account.name} · {account.provider}</option>)}</Select><Select value={serviceName} onValueChange={setServiceName} label="Servicio"><option value="">Todos los servicios</option>{(options?.services ?? []).map((service) => <option key={service} value={service}>{service}</option>)}</Select></div>
    {error !== null && <><Message tone="error" text={error} /><div className="flex gap-2"><button onClick={() => void load()} className="rounded-lg border border-zinc-600 px-3 py-2 text-sm font-bold">Reintentar</button></div></>}{notice !== null && <Message tone="success" text={notice} />}
    {creating && <CreateBudgetForm onSubmit={create} options={options} />}
    {loading ? <p className="text-zinc-400" aria-live="polite">Cargando presupuestos…</p> : budgets.length === 0 ? <div className="rounded-xl border border-dashed border-zinc-700 p-10 text-center text-zinc-400"><p className="font-bold text-white">No hay presupuesto configurado para este período.</p><p className="mt-2 text-sm">Un presupuesto compara el gasto FOCUS con un límite mensual y genera alertas por umbral.</p>{canManage && <button onClick={() => setCreating(true)} className="mt-4 rounded-lg bg-tak-yellow px-4 py-2 text-sm font-bold text-zinc-950">Crear presupuesto</button>}</div> : <div className="grid gap-4">{budgets.map((budget) => <BudgetCard key={budget.id} budget={budget} performance={performance[budget.id]} alerts={alerts[budget.id] ?? []} canManage={canManage} onEvaluate={() => void evaluateBudgets(token, budget.id).then(() => { setNotice('Umbrales evaluados.'); return load(); }).catch((cause) => setError(message(cause, 'No fue posible evaluar el presupuesto.')))} onEdit={() => void edit(budget)} onArchive={() => { if (window.confirm('¿Archivar este presupuesto?')) void archiveBudget(token, budget.id).then(load).catch((cause) => setError(message(cause, 'No fue posible archivar el presupuesto.'))); }} onOpenAllocation={onOpenAllocation} />)}</div>}</div>;
}
function CreateBudgetForm({ onSubmit, options }: { readonly onSubmit: (event: FormEvent<HTMLFormElement>) => void; readonly options: CostDataOptions | null }) { const [scope, setScope] = useState<BudgetScope>('TENANT'); return <form onSubmit={onSubmit} className="ui-surface grid gap-3 p-5 md:grid-cols-3"><p className="md:col-span-3 text-sm text-zinc-400">1. Elija el alcance. 2. Defina el límite y los umbrales. El presupuesto se guardará para el período seleccionado.</p><Select name="scope" value={scope} onValueChange={(value) => setScope(value as BudgetScope)} label="Alcance"><option value="TENANT">Tenant completo</option><option value="SERVICE">Un servicio</option><option value="CLOUD_ACCOUNT">Una cuenta cloud</option><option value="ALLOCATION_DESTINATION">Destino de asignación</option></Select>{scope === 'ALLOCATION_DESTINATION' && <Field name="scopeKey" label="Destino exacto" placeholder="Ej. centro-costos:plataforma" required />}{scope === 'SERVICE' && <Select name="serviceName" label="Servicio"><option value="">Seleccione un servicio</option>{(options?.services ?? []).map((item) => <option key={item}>{item}</option>)}</Select>}{scope === 'CLOUD_ACCOUNT' && <Select name="cloudAccountId" label="Cuenta cloud"><option value="">Seleccione una cuenta</option>{(options?.cloudAccounts ?? []).map((item) => <option key={item.id} value={item.id}>{item.name} · {item.provider}</option>)}</Select>}<Field name="amount" label="Límite mensual" type="number" required min="0.01" step="0.01"/><Select name="currency" label="Moneda"><option value="USD">USD</option>{(options?.currencies ?? []).filter((item) => item !== 'USD').map((item) => <option key={item}>{item}</option>)}</Select><Field name="warningThreshold" label="Advertencia (%)" type="number" defaultValue="80" required min="1" max="99"/><Field name="criticalThreshold" label="Crítico (%)" type="number" defaultValue="90" required min="1" max="100"/><Field name="exceededThreshold" label="Excedido (%)" type="number" defaultValue="100" required min="1"/><button className="ui-button ui-button-primary min-h-11">Guardar presupuesto</button></form>; }
function BudgetCard({ budget, performance, alerts, canManage, onEvaluate, onEdit, onArchive, onOpenAllocation }: { readonly budget: Budget; readonly performance?: BudgetPerformance; readonly alerts: readonly Alert[]; readonly canManage: boolean; readonly onEvaluate: () => void; readonly onEdit: () => void; readonly onArchive: () => void; readonly onOpenAllocation: () => void }) { const hasActual = performance?.actualCostAvailable === true; const ratio = hasActual ? Math.min(performance?.consumedPercent ?? 0, 100) : 0; return <article className="ui-surface p-5"><div className="flex justify-between gap-4"><div><h2 className="font-bold text-white">{budget.scope === 'TENANT' ? 'Tenant completo' : budget.serviceName ?? budget.scopeKey}</h2><p className="text-sm text-zinc-500">{budget.currency} {budget.amount.toFixed(2)} · {scopeLabel(budget.scope)}</p></div><span className="ui-status">{healthLabel(performance?.health)}</span></div><div className="mt-4 h-2 overflow-hidden rounded bg-zinc-800"><div className="h-full bg-tak-yellow" style={{ width: `${ratio}%` }} /></div><div className="mt-3 grid gap-3 text-sm md:grid-cols-4"><p>Gasto real: <b>{hasActual ? `${budget.currency} ${performance!.actualCost.toFixed(2)}` : 'Pendiente de cierre'}</b></p><p>Disponible: <b>{hasActual ? `${budget.currency} ${performance!.remainingBudget.toFixed(2)}` : 'Pendiente de cierre'}</b></p><p>Forecast: <b>{performance?.forecastCost === undefined ? 'No disponible' : `${budget.currency} ${performance.forecastCost.toFixed(2)}`}</b></p><p>Alertas: <b>{alerts.length === 0 ? 'Ninguna' : alerts.map((alert) => alert.level).join(', ')}</b></p></div><div className="mt-4 flex flex-wrap gap-3 text-sm">{budget.scope !== 'TENANT' && <button onClick={onOpenAllocation} className="ui-button ui-button-quiet px-0">Ver asignación de costos</button>}{canManage && <><button onClick={onEvaluate} className="ui-button ui-button-secondary min-h-9 px-3 text-xs">Evaluar umbrales</button><button onClick={onEdit} className="ui-button ui-button-quiet min-h-9 px-0">Editar importe</button><button onClick={onArchive} className="ui-button ui-button-quiet min-h-9 px-0 text-red-300">Archivar</button></>}</div></article>; }
function Select({ label, children, onValueChange, ...props }: React.SelectHTMLAttributes<HTMLSelectElement> & { readonly label: string; readonly onValueChange?: (value: string) => void }) { return <label className="grid gap-1 text-xs font-bold text-zinc-400">{label}<select {...props} onChange={(event) => onValueChange?.(event.target.value)} className={fieldClass}>{children}</select></label>; }
function Field({ label, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { readonly label: string }) { return <label className="grid gap-1 text-xs font-bold text-zinc-400">{label}<input {...props} className={fieldClass}/></label>; }
function Hint({ text, onUse }: { readonly text: string; readonly onUse: () => void }) { return <div className="ui-callout ui-callout-accent flex flex-wrap items-center justify-between gap-3 text-sm"><span>{text} Por eso este período puede no tener gasto.</span><button onClick={onUse} className="ui-button ui-button-secondary min-h-9 px-3 text-xs">Usar período disponible</button></div>; }
function Message({ tone, text }: { readonly tone: 'error' | 'success'; readonly text: string }) { return <p className={`p-3 text-sm ${tone === 'error' ? 'ui-alert-danger' : 'ui-alert-positive'}`} aria-live="polite">{text}</p>; }
function healthLabel(value: BudgetPerformance['health'] | undefined): string { return value === 'HEALTHY' ? 'Saludable' : value === 'WARNING' ? 'Advertencia' : value === 'CRITICAL' ? 'Crítico' : value === 'EXCEEDED' ? 'Excedido' : value === 'UNAVAILABLE' ? 'Sin cierre financiero' : 'Calculando'; }
function scopeLabel(scope: BudgetScope): string { return scope === 'TENANT' ? 'Tenant' : scope === 'SERVICE' ? 'Servicio' : scope === 'CLOUD_ACCOUNT' ? 'Cuenta cloud' : 'Destino de asignación'; }
function message(cause: unknown, fallback: string): string { return cause instanceof Error ? cause.message : fallback; }
function currentMonth(): string { const date = new Date(); return `${date.getUTCFullYear()}-${String(date.getUTCMonth() + 1).padStart(2, '0')}`; }
const fieldClass = 'ui-control min-h-11 p-2 outline-none';
