import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react';
import { CostAllocationRuleForm } from './CostAllocationRuleForm';
import { readCostAllocationRule, toCostAllocationInput } from './costAllocationUi';
import { CostAllocationSharedTotals } from './CostAllocationSharedTotals';
import { activateCostAllocationRule, archiveCostAllocationRule, closeCostAllocationPeriod, createCostAllocationRule, downloadCostAllocationCsv, fetchCostAllocationClosures, fetchCostAllocationComparison, fetchCostAllocationRules, fetchCostAllocationSummary, fetchCostDataOptions, fetchUnallocatedCosts, fetchValueRealizationDestinations, previewCostAllocationRule, updateCostAllocationRule, type AllocationPreview, type AllocationSummary, type CostAllocationClosure, type CostAllocationRule, type CostAllocationRuleInput, type CostDataOptions, type ValueRealizationDestinationSummary } from '../services/api';

type Filters = { readonly cloudAccountId?: string; readonly serviceName?: string; readonly currency?: string; readonly destination?: string };

export default function CostAllocation({ token, canManage }: { readonly token: string; readonly canManage: boolean }) {
  const [period, setPeriod] = useState(currentMonth());
  const [filters, setFilters] = useState<Filters>({});
  const [rules, setRules] = useState<readonly CostAllocationRule[]>([]);
  const [summary, setSummary] = useState<readonly AllocationSummary[]>([]);
  const [previousSummary, setPreviousSummary] = useState<readonly AllocationSummary[]>([]);
  const [closures, setClosures] = useState<readonly CostAllocationClosure[]>([]);
  const [unallocated, setUnallocated] = useState<readonly UnallocatedItem[]>([]);
  const [creating, setCreating] = useState(false);
  const [preview, setPreview] = useState<AllocationPreview | null>(null);
  const [options, setOptions] = useState<CostDataOptions | null>(null);
  const [destinationSavings, setDestinationSavings] = useState<readonly ValueRealizationDestinationSummary[]>([]);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    try {
      const results = await Promise.allSettled([
        fetchCostAllocationRules(token),
        fetchCostAllocationSummary(token, period, { ...filters, allocationKey: filters.destination }),
        fetchCostAllocationComparison(token, period, { ...filters, allocationKey: filters.destination }),
        fetchUnallocatedCosts(token, period, filters),
        fetchCostAllocationClosures(token, period),
      ]);
      const [ruleResult, summaryResult, comparisonResult, unallocatedResult, closureResult] = results;
      if (ruleResult.status === 'fulfilled') setRules(ruleResult.value.rules);
      if (summaryResult.status === 'fulfilled') setSummary(summaryResult.value.summary);
      if (comparisonResult.status === 'fulfilled') setPreviousSummary(comparisonResult.value.comparison.previousSummary);
      if (unallocatedResult.status === 'fulfilled') setUnallocated(unallocatedResult.value.items);
      if (closureResult.status === 'fulfilled') setClosures(closureResult.value.closures);
      setError(results.some((result) => result.status === 'rejected') ? 'Algunos bloques no pudieron actualizarse. Los datos disponibles permanecen visibles.' : null);
    } catch (cause) { setError(message(cause, 'No fue posible cargar la asignación de costos')); }
  }, [filters, period, token]);

  useEffect(() => { void Promise.resolve().then(load); }, [load]);
  useEffect(() => { void fetchCostDataOptions(token, period).then((response) => setOptions(response.options)).catch(() => setOptions(null)); }, [period, token]);
  useEffect(() => { void fetchValueRealizationDestinations(token, period, filters.currency).then((response) => setDestinationSavings(response.destinations)).catch(() => setDestinationSavings([])); }, [filters.currency, period, token]);
  const visibleSummary = useMemo(() => summary.filter((item) => (filters.currency === undefined || item.currency === filters.currency) && (filters.destination === undefined || item.dimensions.some((dimension) => dimension.allocationKey.toLowerCase().includes(filters.destination!.toLowerCase())))), [filters.currency, filters.destination, summary]);
  const closureStatus = closures.some((closure) => closure.status === 'CLOSED') ? 'CERRADO' : closures.some((closure) => closure.status === 'REPLACED') ? 'REEMPLAZADO' : visibleSummary.length > 0 ? 'LISTO' : 'ABIERTO';

  const create = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const form = new FormData(event.currentTarget); const rule = readCostAllocationRule(form);
    try { if (form.get('action') === 'preview') { await previewRule(rule); return; } await createCostAllocationRule(token, rule); setCreating(false); await load(); }
    catch (cause) { setError(message(cause, 'No fue posible crear la regla')); }
  };
  const previewRule = async (rule: CostAllocationRuleInput, ruleId?: string) => {
    try { setPreview((await previewCostAllocationRule(token, rule, period, ruleId)).preview); setError(null); }
    catch (cause) { setError(message(cause, 'No fue posible previsualizar la regla')); }
  };
  const editRule = async (rule: CostAllocationRule) => {
    const name = window.prompt('Nombre de la regla', rule.name); if (name === null) return;
    const priority = window.prompt('Prioridad (menor número = mayor prioridad)', String(rule.priority)); if (priority === null) return;
    const parsed = Number(priority); if (!Number.isInteger(parsed) || parsed < 0 || name.trim() === '') { setError('El nombre y la prioridad son obligatorios.'); return; }
    try { await updateCostAllocationRule(token, rule.id, { name: name.trim(), priority: parsed }); await load(); }
    catch (cause) { setError(message(cause, 'No fue posible editar la regla')); }
  };
  const exportCsv = async () => {
    try { const blob = new Blob([await downloadCostAllocationCsv(token, period)], { type: 'text/csv;charset=utf-8' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `showback-${period}.csv`; link.click(); URL.revokeObjectURL(url); }
    catch (cause) { setError(message(cause, 'No fue posible exportar el CSV')); }
  };
  const closePeriod = async () => {
    if (!window.confirm(`Confirmar cierre de ${period}. Los costos sin asignar quedarán visibles y no se redistribuirán automáticamente.`)) return;
    const hasClosed = closures.some((closure) => closure.status === 'CLOSED');
    const replacementReason = hasClosed ? window.prompt('Indique el motivo para reemplazar el cierre anterior:') : undefined;
    if (hasClosed && (replacementReason === null || (replacementReason ?? '').trim() === '')) { setError('El motivo del reemplazo es obligatorio.'); return; }
    try { const response = await closeCostAllocationPeriod(token, period, replacementReason === null ? undefined : replacementReason); setClosures(response.closures); setError(null); }
    catch (cause) { setError(message(cause, 'No fue posible cerrar el período')); }
  };

  return <div className="space-y-6">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-black">Asignación de costos</h1><p className="text-zinc-400">Showback determinístico por reglas, dimensiones FOCUS y etiquetas.</p></div><div className="flex flex-wrap gap-2"><input aria-label="Periodo" type="month" value={period} onChange={(event) => setPeriod(event.target.value)} className={fieldClass}/><button onClick={() => void exportCsv()} className="rounded border border-zinc-700 px-4 font-bold">Exportar CSV</button>{canManage && <button onClick={() => setCreating((open) => !open)} className="rounded bg-tak-yellow px-4 font-bold text-zinc-950">Nueva regla</button>}</div></header>
    {options?.latestPeriod !== undefined && options.latestPeriod !== period && <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-tak-yellow/30 bg-tak-yellow/10 p-4 text-sm text-tak-yellow"><span>El último período con costos disponibles es {options.latestPeriod}. Este período puede no tener datos.</span><button onClick={() => setPeriod(options.latestPeriod!)} className="rounded border border-tak-yellow/50 px-3 py-2 font-bold">Usar período disponible</button></div>}
    <div className="grid gap-2 md:grid-cols-4"><select aria-label="Cuenta cloud" value={filters.cloudAccountId ?? ''} onChange={(event) => setFilters((value) => ({ ...value, cloudAccountId: blank(event.target.value) }))} className={fieldClass}><option value="">Todas las cuentas</option>{(options?.cloudAccounts ?? []).map((account) => <option key={account.id} value={account.id}>{account.name} · {account.provider}</option>)}</select><select aria-label="Servicio" value={filters.serviceName ?? ''} onChange={(event) => setFilters((value) => ({ ...value, serviceName: blank(event.target.value) }))} className={fieldClass}><option value="">Todos los servicios</option>{(options?.services ?? []).map((service) => <option key={service}>{service}</option>)}</select><select aria-label="Moneda" value={filters.currency ?? ''} onChange={(event) => setFilters((value) => ({ ...value, currency: blank(event.target.value) }))} className={fieldClass}><option value="">Todas las monedas</option>{(options?.currencies ?? []).map((currency) => <option key={currency}>{currency}</option>)}</select><input value={filters.destination ?? ''} onChange={(event) => setFilters((value) => ({ ...value, destination: blank(event.target.value) }))} placeholder="Centro, proyecto, equipo o ambiente" className={fieldClass}/></div>
    {error !== null && <p className="rounded border border-red-500/40 p-3 text-red-300">{error}</p>}
    {creating && <CostAllocationRuleForm onSubmit={create} options={options}/>} {preview !== null && <section className="rounded-xl border border-tak-yellow/40 bg-tak-yellow/10 p-4"><div className="flex justify-between gap-4"><div><h2 className="font-bold">Previsualización sin guardar</h2><p className="text-sm text-zinc-300">Muestra la cobertura que tendría esta regla en {period}; no modifica costos ni reglas.</p></div><button onClick={() => setPreview(null)} className="text-sm">Cerrar</button></div><p className="mt-2 text-sm">Coincidiría con {preview.metricCount} líneas y {preview.resourceCount} recursos. Reglas usadas: {preview.rulesUsed.length === 0 ? 'ninguna' : preview.rulesUsed.map((rule) => `${rule.name} · v${rule.configurationVersion}`).join(' | ')}.</p><AllocationCards summary={preview.summary}/><p className="mt-2 text-xs text-zinc-400">Período anterior: {preview.previousSummary.map((item) => `${item.currency} ${item.totalCost.toFixed(2)}`).join(' · ') || 'sin datos'}.</p>{preview.examples.length > 0 && <p className="mt-3 text-xs text-zinc-400">Ejemplos: {preview.examples.map((item) => `${item.currency} ${item.cost.toFixed(2)} · ${item.serviceName}`).join(' | ')}</p>}<div className="mt-4 rounded border border-zinc-700/60 bg-zinc-950/30 p-3"><h3 className="font-bold">Impacto financiero</h3>{preview.financialImpact.budgets.length === 0 ? <p className="mt-1 text-xs text-zinc-400">No hay presupuestos por destino para este período.</p> : <div className="mt-2 space-y-1 text-xs">{preview.financialImpact.budgets.map((item) => <p key={`${item.currency}-${item.allocationKey}`}>{item.currency} · {item.allocationKey}: gasto proyectado {item.projectedCost.toFixed(2)} de {item.budgetAmount.toFixed(2)} ({item.consumedPercent.toFixed(1)}%).</p>)}</div>}<p className="mt-2 text-xs text-zinc-400">Ahorro con evidencia cerrada — potencial: {savingsByCurrency(preview.financialImpact.savings, 'potentialSavings')} · aprobado: {savingsByCurrency(preview.financialImpact.savings, 'approvedSavings')} · verificado: {savingsByCurrency(preview.financialImpact.savings, 'verifiedSavings')}. No se proyecta ahorro nuevo hasta cerrar y ejecutar.</p></div></section>}
    <AllocationCards summary={visibleSummary}/><CostAllocationSharedTotals summary={visibleSummary}/>
    <section className="rounded-xl border border-zinc-800 bg-zinc-900 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold">Estado del período</h2><p className="mt-1 text-sm text-zinc-400">Checklist previo al cierre de {period}.</p></div><span className="rounded border border-tak-yellow/40 px-3 py-1 text-sm font-bold text-tak-yellow">{closureStatus}</span></div><ul className="mt-3 grid gap-2 text-sm text-zinc-300 md:grid-cols-2"><li>{visibleSummary.length > 0 ? '✓' : '○'} Fuente de costos disponible para el período.</li><li>{rules.some((rule) => rule.status === 'ACTIVE') ? '✓' : '○'} Reglas activas cargadas y filtradas por tenant.</li><li>{visibleSummary.every(totalsBalance) ? '✓' : '○'} Totales separados por moneda.</li><li>{unallocated.length === 0 ? '✓' : '!' } Costos sin asignar: {unallocated.length === 0 ? 'ninguno detectado' : 'se confirmarán explícitamente al cerrar'}.</li><li className="md:col-span-2 text-zinc-500">Los trabajos de facturación activos y la inmutabilidad de la fuente se validan en el backend al confirmar el cierre.</li></ul></section>
    <section className="rounded-xl border border-zinc-800 bg-zinc-900 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold">Valor financiero por destino</h2><p className="text-sm text-zinc-400">Solo incluye ahorros vinculados a una línea de costo cerrada, recurso canónico y hash de métrica exactos.</p></div><span className="text-xs text-zinc-500">Sin evidencia exacta no se atribuye ahorro.</span></div>{destinationSavings.length === 0 ? <p className="mt-3 text-sm text-zinc-500">No hay ahorros atribuibles por destino para este período.</p> : <div className="mt-3 space-y-2">{destinationSavings.filter((item) => filters.destination === undefined || item.allocationKey.toLowerCase().includes(filters.destination.toLowerCase())).map((item) => <div key={`${item.currency}-${item.allocationKey}`} className="grid gap-2 border-b border-zinc-800 py-3 text-sm md:grid-cols-5"><span className="font-medium">{item.allocationKey === 'UNALLOCATED' ? 'Sin asignar' : item.allocationKey}<small className="block text-xs text-zinc-500">{item.attributedRecommendations} oportunidades con evidencia</small></span><span>{item.currency} {item.potentialSavings.toFixed(2)}<small className="block text-xs text-zinc-500">Potencial</small></span><span>{item.currency} {item.approvedSavings.toFixed(2)}<small className="block text-xs text-zinc-500">Aprobado</small></span><span className="text-tak-yellow">{item.currency} {item.verifiedSavings.toFixed(2)}<small className="block text-xs text-zinc-500">Verificado</small></span><span className="text-sky-200">{item.currency} {item.observedSavings.toFixed(2)}<small className="block text-xs text-zinc-500">Observado</small></span></div>)}</div>}</section>
    <section className="rounded-xl border border-zinc-800 bg-zinc-900 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold">Comparación de cobertura mensual</h2><p className="text-sm text-zinc-400">Compara cuánto gasto tiene una dimensión y cuánto sigue sin asignar.</p></div>{canManage && <button onClick={() => void closePeriod()} className="rounded bg-tak-yellow px-3 py-2 text-sm font-bold text-zinc-950">Cerrar período</button>}</div>{visibleSummary.map((item) => { const previous = previousSummary.find((candidate) => candidate.currency === item.currency); const delta = item.coveragePercent - (previous?.coveragePercent ?? 0); return <p key={item.currency} className="mt-2 text-sm">{item.currency}: {item.coveragePercent.toFixed(1)}% este mes · {previous?.coveragePercent.toFixed(1) ?? 'sin datos'}% mes anterior <b className={delta >= 0 ? 'text-green-300' : 'text-red-300'}>({delta >= 0 ? '+' : ''}{delta.toFixed(1)} pp)</b></p>; })}</section>
    {closures.length > 0 && <section className="rounded-xl border border-emerald-800/60 bg-emerald-950/20 p-4"><h2 className="font-bold">Cierres reproducibles de {period}</h2><p className="mt-1 text-sm text-zinc-400">Cada moneda se cierra por separado. Un reemplazo conserva la versión anterior para auditoría.</p><div className="mt-3 space-y-2">{closures.map((closure) => <div key={closure.id} className="flex flex-wrap justify-between gap-3 rounded border border-zinc-800 p-3 text-sm"><span><b>{closure.currency}</b> · versión {closure.version} · {closure.status === 'CLOSED' ? 'Cerrado' : 'Reemplazado'}<small className="ml-2 text-zinc-500">Fuente {closure.sourceHash.slice(0, 10)}…</small></span><span>Total {closure.sourceTotal.toFixed(2)} · asignado {closure.allocatedTotal.toFixed(2)} · sin asignar {closure.unallocatedTotal.toFixed(2)}</span></div>)}</div></section>}
    <section className="rounded-xl border border-zinc-800 bg-zinc-900 p-4"><h2 className="font-bold">Distribución del gasto</h2>{visibleSummary.length === 0 ? <p className="mt-3 text-zinc-500">No hay costos para los filtros seleccionados.</p> : <div className="mt-3 space-y-2">{visibleSummary.flatMap((item) => item.dimensions.map((dimension) => ({ ...dimension, currency: item.currency }))).filter((item) => filters.destination === undefined || item.allocationKey.toLowerCase().includes(filters.destination.toLowerCase())).map((item) => <p key={`${item.currency}-${item.allocationKey}`} className="flex justify-between gap-3 text-sm"><span>{item.allocationKey === 'UNALLOCATED' ? 'Sin asignar' : item.allocationKey} <small className="text-zinc-500">· {item.metricCount} líneas · {item.resourceCount} recursos</small></span><b>{item.currency} {item.cost.toFixed(2)}</b></p>)}</div>}</section>
    <section className="rounded-xl border border-zinc-800 bg-zinc-900 p-4"><h2 className="font-bold">Reglas</h2>{rules.length === 0 ? <p className="mt-3 text-zinc-500">No hay reglas configuradas. Cree una regla para asignar el gasto sin etiqueta.</p> : <div className="mt-3 space-y-2">{rules.map((rule) => { const previewReady = rule.configurationHash !== undefined && rule.lastPreviewedHash === rule.configurationHash; return <div key={rule.id} className="flex flex-wrap justify-between gap-3 border-b border-zinc-800 py-3"><div><b>{rule.name}</b> <span className="text-xs text-zinc-500">Prioridad {rule.priority} · {labelStatus(rule.status)} · {rule.allocationMode === 'SPLIT' ? `Distribución ${rule.allocationTargets.map((item) => `${item.percentage}%`).join(' + ')}` : 'Directa'} · v{rule.configurationVersion}</span><p className="text-sm text-zinc-400">{criterion(rule)} → {target(rule)}</p></div>{canManage && <div className="flex flex-wrap gap-3 text-sm"><button onClick={() => void previewRule(toCostAllocationInput(rule), rule.id)}>Previsualizar</button><button onClick={() => void editRule(rule)}>Editar</button>{rule.status === 'DRAFT' && <><button disabled={!previewReady} onClick={() => void activateCostAllocationRule(token, rule.id).then(load).catch((cause) => setError(message(cause, 'Previsualice la regla antes de activarla.')))} className="disabled:cursor-not-allowed disabled:opacity-40">Activar</button>{!previewReady && <span className="self-center text-xs text-tak-yellow">Previsualice antes de activar</span>}</>}{rule.status !== 'ARCHIVED' && <button className="text-red-300" onClick={() => void archiveCostAllocationRule(token, rule.id).then(load).catch((cause) => setError(message(cause, 'No fue posible archivar la regla')))}>Archivar</button>}</div>}</div>; })}</div>}</section>
    <section className="rounded-xl border border-zinc-800 bg-zinc-900 p-4"><h2 className="font-bold">Costos sin asignar</h2>{unallocated.length === 0 ? <p className="mt-3 text-zinc-500">No hay costos sin asignar para este periodo y filtros.</p> : <div className="mt-3 space-y-2">{unallocated.slice(0, 50).map((item, index) => <p key={`${item.cloudAccountId}-${item.serviceName}-${index}`} className="text-sm"><b>{item.currency} {item.cost.toFixed(2)}</b> · {item.serviceName} · {item.cloudAccountId} {item.resourceId !== undefined ? `· ${item.resourceId}` : ''}<span className="text-zinc-500"> — {item.suggestedCriteria.join(', ')}</span></p>)}</div>}</section>
  </div>;
}

function AllocationCards({ summary }: { readonly summary: readonly AllocationSummary[] }) { return <section className="grid gap-3 md:grid-cols-3">{summary.map((item) => <article key={item.currency} className="rounded-xl border border-zinc-800 bg-zinc-900 p-4"><p className="text-xs uppercase text-zinc-500">{item.currency} · Cobertura</p><p className="text-3xl font-black">{item.coveragePercent.toFixed(1)}%</p><p className="text-sm text-zinc-400">Total {item.currency} {item.totalCost.toFixed(2)} · Asignado {item.currency} {item.allocatedCost.toFixed(2)} · Sin asignar {item.currency} {item.unallocatedCost.toFixed(2)}</p></article>)}</section>; }
function criterion(rule: CostAllocationRule): string { return [rule.cloudAccountId, rule.provider, rule.serviceName, rule.regionId, rule.resourceId, rule.tagKey === undefined ? undefined : `${rule.tagKey}=${rule.tagValue}`].filter(Boolean).join(' · '); }
function target(rule: CostAllocationRule): string { return [rule.costCenter, rule.businessUnit, rule.project, rule.team, rule.environment].filter(Boolean).join(' · '); }
function labelStatus(status: CostAllocationRule['status']): string { return status === 'DRAFT' ? 'Borrador' : status === 'ACTIVE' ? 'Activa' : 'Archivada'; }
function blank(value: string): string | undefined { const trimmed = value.trim(); return trimmed === '' ? undefined : trimmed; }
function message(cause: unknown, fallback: string): string { return cause instanceof Error ? cause.message : fallback; }
function currentMonth(): string { const date = new Date(); return `${date.getUTCFullYear()}-${String(date.getUTCMonth() + 1).padStart(2, '0')}`; }
function totalsBalance(item: AllocationSummary): boolean { return Math.abs(item.totalCost - item.allocatedCost - item.unallocatedCost) < 0.000001; }
function savingsByCurrency(items: readonly ValueRealizationDestinationSummary[], field: 'potentialSavings' | 'approvedSavings' | 'verifiedSavings'): string { const totals = new Map<string, number>(); for (const item of items) totals.set(item.currency, (totals.get(item.currency) ?? 0) + item[field]); return [...totals.entries()].map(([currency, value]) => `${currency} ${value.toFixed(2)}`).join(' · ') || 'sin evidencia exacta'; }
const fieldClass = 'rounded border border-zinc-700 bg-zinc-950 p-2';
type UnallocatedItem = { readonly cost: number; readonly currency: string; readonly serviceName: string; readonly cloudAccountId: string; readonly resourceId?: string; readonly suggestedCriteria: readonly string[] };
