import { useState, type FormEvent } from 'react';
import type { CostDataOptions } from '../services/api';

export function CostAllocationRuleForm({ onSubmit, options }: { readonly onSubmit: (event: FormEvent<HTMLFormElement>) => void; readonly options: CostDataOptions | null }) {
  const [mode, setMode] = useState<'DIRECT' | 'SPLIT'>('DIRECT');
  const [targetCount, setTargetCount] = useState(2);
  const [percentages, setPercentages] = useState<readonly number[]>([50, 50]);
  const handleSubmit = (event: FormEvent<HTMLFormElement>) => { if (mode === 'SPLIT' && Math.round(percentages.reduce((sum, value) => sum + value, 0) * 10000) !== 1_000_000) { event.preventDefault(); return; } onSubmit(event); };
  return <form onSubmit={handleSubmit} className="grid gap-2 rounded-xl border border-zinc-800 bg-zinc-900 p-4 md:grid-cols-3">
    <p className="md:col-span-3 text-sm text-zinc-400">1. Defina el criterio de costo. 2. Indique el destino. 3. Previsualice antes de activar la regla.</p>
    <input required name="name" placeholder="Nombre de la regla" className={fieldClass}/><input required type="number" min="0" defaultValue="100" name="priority" placeholder="Prioridad" className={fieldClass}/>
    <select name="allocationMode" value={mode} onChange={(event) => setMode(event.target.value as 'DIRECT' | 'SPLIT')} className={fieldClass}><option value="DIRECT">Asignación directa</option><option value="SPLIT">Distribución compartida</option></select>
    <select name="cloudAccountId" className={fieldClass}><option value="">Cualquier cuenta</option>{(options?.cloudAccounts ?? []).map((account) => <option key={account.id} value={account.id}>{account.name} · {account.provider}</option>)}</select>
    <select name="provider" className={fieldClass}><option value="">Cualquier proveedor</option><option>OCI</option><option>AWS</option></select><select name="serviceName" className={fieldClass}><option value="">Cualquier servicio</option>{(options?.services ?? []).map((service) => <option key={service}>{service}</option>)}</select>
    {mode === 'DIRECT' ? <><input name="costCenter" placeholder="Centro de costo (destino)" className={fieldClass}/><input name="project" placeholder="Proyecto (destino)" className={fieldClass}/><input name="team" placeholder="Equipo (destino)" className={fieldClass}/></> : <div className="md:col-span-3 rounded border border-tak-yellow/30 p-3"><div className="flex items-center justify-between gap-2"><p className="text-sm text-zinc-300">Destinos y porcentajes: <b className={percentages.reduce((sum, value) => sum + value, 0) === 100 ? 'text-green-300' : 'text-tak-yellow'}>{percentages.reduce((sum, value) => sum + value, 0).toFixed(4)} % de 100 %</b>.</p><button type="button" onClick={() => { setTargetCount((count) => Math.min(6, count + 1)); setPercentages((values) => [...values, 0]); }} className="text-sm text-tak-yellow">Agregar destino</button></div><div className="mt-2 grid gap-2 md:grid-cols-2">{Array.from({ length: targetCount }, (_, index) => <div key={index} className="grid gap-2 rounded border border-zinc-800 p-2"><b className="text-sm">Destino {index + 1}</b><input required type="number" min="0.0001" max="100" step="0.0001" name={`target${index}Percentage`} defaultValue={index < 2 ? '50' : ''} onChange={(event) => setPercentages((values) => values.map((value, valueIndex) => valueIndex === index ? Number(event.target.value) || 0 : value))} placeholder="Porcentaje" className={fieldClass}/><input name={`target${index}CostCenter`} placeholder="Centro de costo" className={fieldClass}/><input name={`target${index}BusinessUnit`} placeholder="Unidad de negocio" className={fieldClass}/><input name={`target${index}Project`} placeholder="Proyecto" className={fieldClass}/><input name={`target${index}Team`} placeholder="Equipo" className={fieldClass}/><input name={`target${index}Environment`} placeholder="Ambiente" className={fieldClass}/>{targetCount > 2 && index === targetCount - 1 && <button type="button" onClick={() => { setTargetCount((count) => Math.max(2, count - 1)); setPercentages((values) => values.slice(0, -1)); }} className="text-left text-xs text-red-300">Quitar último destino</button>}</div>)}</div></div>}
    <details className="md:col-span-3 rounded border border-zinc-800 p-3 text-sm text-zinc-400"><summary className="cursor-pointer font-bold text-white">Criterios y destinos avanzados</summary><div className="mt-3 grid gap-2 md:grid-cols-3"><input name="description" placeholder="Descripción" className={fieldClass}/><input name="regionId" placeholder="Región" className={fieldClass}/><input name="resourceId" placeholder="Recurso" className={fieldClass}/><input name="tagKey" placeholder="Etiqueta" className={fieldClass}/><input name="tagValue" placeholder="Valor de etiqueta" className={fieldClass}/><input name="businessUnit" placeholder="Unidad de negocio" className={fieldClass}/><input name="environment" placeholder="Ambiente" className={fieldClass}/></div></details>
    <button name="action" value="preview" className="min-h-11 rounded border border-tak-yellow/60 font-bold text-tak-yellow">Previsualizar</button><button name="action" value="save" className="min-h-11 rounded bg-white font-bold text-zinc-950">Guardar borrador</button>
  </form>;
}

const fieldClass = 'rounded border border-zinc-700 bg-zinc-950 p-2';
